name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  pull-requests: write
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:
    uses: romancitodev/workflows/.github/workflows/rust-ci.yml@main
    with:
      strict-mode: true
      cargo-test-flags: "--lib"
